### ISSUE TITLE
[patch] Remove the obsolete Maemo support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [huzheng001/stardict-3#27]
```
Hildon will likely never be ported to GTK+ 3, so this was dead code.
```

Original issue reported on code.google.com by `b...@users.sourceforge.net` on 7 Apr 2012 at 4:04

Attachments:
* [patch-stardict-remove-maemo](https://storage.googleapis.com/google-code-attachments/stardict-3/issue-27/comment-0/patch-stardict-remove-maemo)

**Comment by huzheng001** [comment]
Needn't remove.
