### ISSUE TITLE
Hebrew translation (partial and old)

### ISSUE THREAD

**Issue by GreenLunar** [huzheng001/stardict-3#72]
Hello,

Attached a translation in Hebrew.
It is old, and was taken from StarDict 3.0.3.

Please merge it. I hope I would provide updates in the next months.

[stardict-3.0.3.po.gz](https://github.com/huzheng001/stardict-3/files/217782/stardict-3.0.3.po.gz)

**Comment by huzheng001** [comment]
Merged! Try update this file and send the new version to me!!!
https://github.com/huzheng001/stardict-3/blob/master/dict/po/he.po

**Comment by GreenLunar** [comment]
I have made another update.  Would you like me to send it to you by email or send a pull request?

**Comment by GreenLunar** [comment]
Yes? No?

**Comment by huzheng001** [comment]
Both!!!

**Comment by huzheng001** [comment]
Gmail is blocked in China, so I reply late!

Both!! Pull request is better!

2016-04-28 2:11 GMT+08:00 GreenLunar <notifications@github.com>:

> Yes? No?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/huzheng001/stardict-3/issues/72#issuecomment-215177278>
>



-- 
http://www.huzheng.org
