### ISSUE TITLE
Tagged releases and changelog

### ISSUE THREAD

**Issue by baimafeima** [huzheng001/stardict-3#76]
Could you tag your releases and make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by huzheng001** [comment]
We like edit ChangeLog manually!

**Comment by ryandesign** [comment]
Why is this issue closed? There still aren't any tags or releases in this repository.
