### ISSUE TITLE
怎么把stardict的词典转换成dictd能用的？

### ISSUE THREAD

**Issue by xuiv** [huzheng001/stardict-3#84]
没人管了？
dictconv年久失修，你的dict文件没有字条，只有释义，我要一个langdao_ec_gb，想把它转成dictd能用的。

**Comment by tuberry** [comment]
所以，应该怎么转呢？

**Comment by xuiv** [comment]
> 所以，应该怎么转呢？

我转好了，不过忘了方法了。

**Comment by xuiv** [comment]
https://github.com/xuiv/memacs/releases/download/5.0/langdao.tar.bz2

**Comment by tuberry** [comment]
谢谢，我看readme把stardict-tools编译后转成foldoc格式了,但还来得及弄成标准的。
